### ISSUE TITLE
Backend crashes if patron asks for non-returnable question

### ISSUE THREAD

**Issue by TranHVLoc** [Meng-V/smartchatbot#75]
If client asks for some service that cannot be done or not in the domain knowledge, the app will crash
Try:

`Please book a room for 6 people at McVey building today`

**Comment by TranHVLoc** [comment]
Here is the error. It's 400 code - Bad Request. Bad Try-catch from code suspected

> /app/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 400
    at settle (/app/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
